### ISSUE TITLE
cloudflare server default not set as documented in help

### ISSUE THREAD

**Issue by dkerr64** [astlinux-project/ddclient-curl#2]
Help text states that cloudflare server is set to `api.cloudflare.com/client/v4` by default.  It is not... it is set to whatever the last `server=xxx` statement in the .conf file is... even if for a different service.  Only if there is no server= statement will it default to the correct cloudflare URL.

This is caused by ddclient loading some settings into its global config rather than by-service config.

David

**Comment by abelbeck** [comment]
So the best solution is to document to not set server= for Cloudflare ?

**Comment by dkerr64** [comment]
I think the best solution is not to document that it defaults to anything,
and to document explicitly setting server=api.cloudflare.com/client/v4 in
the help text.

I ran into this in the past and fixing it is if I remember right is
non-trivial.  Bottom line is that it appears ddclient was created initially
with just handling one service in the .conf file and then whether by
accident or design evolved to allow multiple services to be updated... and
unless you explicitly set variable=value for a service, it inherits
whatever value was set last... not always desirable but that is what it
does.

David

**Comment by abelbeck** [comment]
> I think the best solution is not to document that it defaults to anything,

Agreed, since the Cloudflare code requires api.cloudflare.com/client/v4 to work.
