### ISSUE TITLE
ipv6 support - google domains

### ISSUE THREAD

**Issue by drizuid** [astlinux-project/ddclient-curl#6]
on your front page, you list providers offering both ipv4 and ipv6 support. Are there any plans to add support for both with google domains? According to their help page, they support both
https://support.google.com/domains/answer/6147083?hl=en

Note: Dynamic DNS works with both IPv4 and IPv6 addresses. 

thanks much!

**Comment by abelbeck** [comment]
That seems quite reasonable to add.  I don't have a Google Domains account to test with, but if anyone reading this wants to create a PR to add IPv6 support for Google Domains we would definitely take a look at it.

**Comment by drizuid** [comment]
actually, we can close this, their documentation is misleading. I just spoke to their support after attempting to leverage their API manually. While they support both ipv6 and ipv4, they do NOT support it concurrently on a single synthetic record. I've submitted a feature request to Google to add this.  Sorry for this bad request, i was going off their documentation :(

that said, `myip` in the API can accept ipv6 or ipv4, but whichever is sent last is the IP it will use.
