### ISSUE TITLE
ddclient uses the ULA

### ISSUE THREAD

**Issue by libertyx82** [astlinux-project/ddclient-curl#7]
On the Reason that the ULA is the first Address, ddclient uses this to Update cloudflare.

How can i skip the ULA so that ddclient uses the global IPv6 Address for the Update

**Comment by abelbeck** [comment]
Hmmm, I guess ULA's also show up as `scope global` here:
https://github.com/astlinux-project/ddclient-curl/blob/master/ddclient#L2289

Looks like an address starting with `fd` should be skipped.

Possibly you can take a stab at a fix PR ?

**Comment by libertyx82** [comment]
Yes the ULA also shows up as scope global

```
inet6 fd00::zzz:xxx:yyy:7c6f/64 scope global dynamic mngtmpaddr noprefixroute
valid_lft 6757sec preferred_lft 3157sec
inet6 2001:16b8:zzz:xxx:20c:yyy:fe79:7d6f/64 scope global dynamic mngtmpaddr noprefixroute
```

i have tried it with 
`if-skip=fd`

But that only skips the fd from the address

> Possibly you can take a stab at a fix PR ?

What du you mean?

**Comment by abelbeck** [comment]
> What do you mean?

@libertyx82 : I was asking if you wanted to try to tweak the perl regular express match to skip `fd` addresses ... if successful create a Pull Request (PR) here on github.

If you are not comfortable doing that, either myself or @dkerr64  should be able to do it.

**Comment by libertyx82** [comment]
I think now i understand what you mean.

This line must be adjusted

`if ($reply =~ /^.*? ([a-f0-9]{1,4}:[a-f0-9:]+:[a-f0-9]{1,4})\/.*/is)`

On the reason that only Global Unicast Addresses are wanted it must be a adjusted that only Addresses that begining with 2000: should be used for the update.

But i am not so good in scripting :) so will this be correct?

`([2001]:[a-f0-9]{1,4}:[a-f0-9:]+:[a-f0-9]{1,4})`

**Comment by libertyx82** [comment]
I think i got it :)

`(20[0-2]{1,2}:[a-f0-9]{1,4}:[a-f0-9:]+:[a-f0-9]{1,4})`

For me it is working

https://github.com/astlinux-project/ddclient-curl/pull/8

**Comment by abelbeck** [comment]
@libertyx82 : Good, but I'm thinking not quite a general enough regex ...

If we agree `2000::/3` is the current GUA address space

```
# netcalc 2000::/3
Address ID      : 0:0:0:0:0:0:0:0/3
Compressed IPv6 : 2000::
Expanded IPv6   : 2000:0000:0000:0000:0000:0000:0000:0000
Prefix address  : e000:0:0:0:0:0:0:0 = length 3
Address type    : Aggregatable Global Unicast Addresses
=>
Network         : 2000:0:0:0:0:0:0:0/3
HostMin         : 2000:0000:0000:0000:0000:0000:0000:0000
HostMax         : 3fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
```
Current:
```
if ($reply =~ /^.*? ([a-f0-9]{1,4}:[a-f0-9:]+:[a-f0-9]{1,4})\/.*/is) {
```
GUA-only:
```
if ($reply =~ /^.*? ([23][a-f0-9]{3}:[a-f0-9:]+:[a-f0-9]{1,4})\/.*/is) {
```
Note that there must be 4 hex digits before the first `:` (colon) given the `/3` mask.

@libertyx82 : could you give this "GUA-only:" regex a try, and if it works for you adjust your PR (or create a new PR).

@dkerr64 : Does this "GUA-only:" look good to you ?

**Comment by libertyx82** [comment]
I have tested it and it works, so i have created a new PR

**Comment by libertyx82** [comment]
https://github.com/astlinux-project/ddclient-curl/pull/9

**Comment by dkerr64** [comment]
> @dkerr64 : Does this "GUA-only:" look good to you ?

Sorry I've been asleep for the past two days.  I do hope you are not asking me to check over the regex... I cannot get my head around regex at the best of times!!  I would just throw a lot of examples at it to check it doesn't break.

But it was certainly a good catch to find that ULAs were getting sent up for registration... we should only be sending GUAs.
